name: Update

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # - name: Install composer dependencies
      #   uses: ramsey/composer-install@v1

      # - name: Run Pint
      #   run: ./vendor/bin/pint

      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Update
